#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
OPEN_PROJECTS=${OPEN_PROJECTS-$HOME/open-projects}
export PYTHONPATH=$PYTHONPATH:/$OPEN_PROJECTS/JCGS_py_server/
$SCRIPT_DIR/storage_client.py --query-key $OPEN_PROJECTS/JCGS_py_server/querykey.pub --reply-key $OPEN_PROJECTS/JCGS_py_server/replykey $*
