#!/usr/bin/python3

# Program to say I have been in touch with someone

import argparse
import csv

def main():
    parser = argparse.ArgumentParser()
    args = parser.parse_args()

if __name__ == '__main__':
    main()
